#include "cli_arg_required.hpp"

namespace wowee {
namespace editor {
namespace cli {

const char* const kArgRequired[] = {
    "--data", "--info", "--info-batches", "--info-textures", "--info-doodads",
    "--info-attachments", "--info-particles", "--info-sequences",
    "--info-bones", "--export-bones-dot",
    "--list-zone-meshes", "--list-zone-audio", "--list-zone-textures",
    "--list-project-meshes", "--list-project-audio",
    "--list-project-textures",
    "--info-zone-models-total", "--info-project-models-total",
    "--list-zone-meshes-detail", "--list-project-meshes-detail", "--info-mesh",
    "--info-mesh-storage-budget", "--info-mesh-stats",
    "--info-wob", "--info-wob-stats", "--info-woc", "--info-wot",
    "--info-wol", "--info-wol-at", "--validate-wol", "--gen-light",
    "--gen-light-cave", "--gen-light-dungeon", "--gen-light-night",
    "--export-wol-json", "--import-wol-json",
    "--export-wow-json", "--import-wow-json",
    "--info-wow", "--validate-wow",
    "--validate-wom",
    "--gen-world-map", "--gen-world-map-instance",
    "--gen-world-map-arena",
    "--info-womx", "--validate-womx",
    "--export-womx-json", "--import-womx-json",
    "--gen-sound-catalog", "--gen-sound-catalog-ambient",
    "--gen-sound-catalog-tavern",
    "--info-wsnd", "--validate-wsnd",
    "--export-wsnd-json", "--import-wsnd-json",
    "--gen-spawns", "--gen-spawns-camp", "--gen-spawns-village",
    "--info-wspn", "--validate-wspn",
    "--export-wspn-json", "--import-wspn-json",
    "--gen-items", "--gen-items-weapons", "--gen-items-armor",
    "--info-wit", "--validate-wit",
    "--export-wit-json", "--import-wit-json",
    "--gen-loot", "--gen-loot-bandit", "--gen-loot-boss",
    "--info-wlot", "--validate-wlot",
    "--export-wlot-json", "--import-wlot-json",
    "--gen-creatures", "--gen-creatures-bandit", "--gen-creatures-merchants",
    "--info-wcrt", "--validate-wcrt",
    "--export-wcrt-json", "--import-wcrt-json",
    "--gen-quests", "--gen-quests-chain", "--gen-quests-daily",
    "--info-wqt", "--validate-wqt",
    "--export-wqt-json", "--import-wqt-json",
    "--gen-objects", "--gen-objects-dungeon", "--gen-objects-gather",
    "--info-wgot", "--validate-wgot",
    "--export-wgot-json", "--import-wgot-json",
    "--gen-factions", "--gen-factions-alliance", "--gen-factions-wildlife",
    "--info-wfac", "--validate-wfac",
    "--export-wfac-json", "--import-wfac-json",
    "--gen-locks", "--gen-locks-dungeon", "--gen-locks-professions",
    "--info-wlck", "--validate-wlck",
    "--export-wlck-json", "--import-wlck-json",
    "--gen-skills", "--gen-skills-professions", "--gen-skills-weapons",
    "--info-wskl", "--validate-wskl",
    "--export-wskl-json", "--import-wskl-json",
    "--gen-spells", "--gen-spells-mage", "--gen-spells-warrior",
    "--info-wspl", "--validate-wspl",
    "--export-wspl-json", "--import-wspl-json",
    "--gen-achievements", "--gen-achievements-bandit", "--gen-achievements-meta",
    "--info-wach", "--validate-wach",
    "--export-wach-json", "--import-wach-json",
    "--gen-trainers", "--gen-trainers-mage", "--gen-trainers-weapons",
    "--info-wtrn", "--validate-wtrn",
    "--export-wtrn-json", "--import-wtrn-json",
    "--gen-gossip", "--gen-gossip-innkeeper", "--gen-gossip-questgiver",
    "--info-wgsp", "--validate-wgsp",
    "--export-wgsp-json", "--import-wgsp-json",
    "--gen-taxi", "--gen-taxi-region", "--gen-taxi-continent",
    "--info-wtax", "--validate-wtax",
    "--export-wtax-json", "--import-wtax-json",
    "--gen-talents", "--gen-talents-warrior", "--gen-talents-mage",
    "--info-wtal", "--validate-wtal",
    "--export-wtal-json", "--import-wtal-json",
    "--gen-maps", "--gen-maps-classic", "--gen-maps-bgarena",
    "--info-wms", "--validate-wms",
    "--export-wms-json", "--import-wms-json",
    "--gen-chars", "--gen-chars-alliance", "--gen-chars-allraces",
    "--info-wchc", "--validate-wchc",
    "--export-wchc-json", "--import-wchc-json",
    "--gen-tokens", "--gen-tokens-pvp", "--gen-tokens-seasonal",
    "--info-wtkn", "--validate-wtkn",
    "--export-wtkn-json", "--import-wtkn-json",
    "--gen-triggers", "--gen-triggers-dungeon", "--gen-triggers-flightpath",
    "--info-wtrg", "--validate-wtrg",
    "--export-wtrg-json", "--import-wtrg-json",
    "--gen-titles", "--gen-titles-pvp", "--gen-titles-achievement",
    "--info-wtit", "--validate-wtit",
    "--export-wtit-json", "--import-wtit-json",
    "--gen-events", "--gen-events-yearly", "--gen-events-weekends",
    "--info-wsea", "--validate-wsea",
    "--export-wsea-json", "--import-wsea-json",
    "--gen-mounts", "--gen-mounts-racial", "--gen-mounts-flying",
    "--info-wmou", "--validate-wmou",
    "--export-wmou-json", "--import-wmou-json",
    "--gen-bg", "--gen-bg-classic", "--gen-bg-arena",
    "--info-wbgd", "--validate-wbgd",
    "--export-wbgd-json", "--import-wbgd-json",
    "--gen-mail", "--gen-mail-holiday", "--gen-mail-auction",
    "--info-wmal", "--validate-wmal",
    "--export-wmal-json", "--import-wmal-json",
    "--gen-gems", "--gen-gems-set", "--gen-gems-enchants",
    "--info-wgem", "--validate-wgem",
    "--export-wgem-json", "--import-wgem-json",
    "--gen-guilds", "--gen-guilds-full", "--gen-guilds-pair",
    "--info-wgld", "--validate-wgld",
    "--export-wgld-json", "--import-wgld-json",
    "--gen-conditions", "--gen-conditions-gated", "--gen-conditions-event",
    "--info-wpcd", "--validate-wpcd",
    "--export-wpcd-json", "--import-wpcd-json",
    "--gen-pets", "--gen-pets-hunter", "--gen-pets-warlock",
    "--info-wpet", "--validate-wpet",
    "--export-wpet-json", "--import-wpet-json",
    "--gen-auction", "--gen-auction-pair", "--gen-auction-restricted",
    "--info-wauc", "--validate-wauc",
    "--export-wauc-json", "--import-wauc-json",
    "--gen-channels", "--gen-channels-city", "--gen-channels-moderated",
    "--info-wchn", "--validate-wchn",
    "--export-wchn-json", "--import-wchn-json",
    "--gen-cinematics", "--gen-cinematics-intros", "--gen-cinematics-quests",
    "--info-wcms", "--validate-wcms",
    "--export-wcms-json", "--import-wcms-json",
    "--gen-glyphs", "--gen-glyphs-warrior", "--gen-glyphs-universal",
    "--info-wgly", "--validate-wgly",
    "--export-wgly-json", "--import-wgly-json",
    "--gen-vehicles", "--gen-vehicles-siege", "--gen-vehicles-flying",
    "--info-wvhc", "--validate-wvhc",
    "--export-wvhc-json", "--import-wvhc-json",
    "--gen-holidays", "--gen-holidays-weekly", "--gen-holidays-special",
    "--info-whol", "--validate-whol",
    "--export-whol-json", "--import-whol-json",
    "--gen-liquids", "--gen-liquids-magical", "--gen-liquids-hazardous",
    "--info-wliq", "--validate-wliq",
    "--export-wliq-json", "--import-wliq-json",
    "--info-magic", "--summary-dir", "--rename-by-magic",
    "--bulk-rename-by-magic", "--touch-tree", "--tree-summary-md",
    "--catalog-grep", "--diff-headers", "--audit-tree",
    "--catalog-pluck", "--catalog-find", "--catalog-by-name",
    "--catalog-id-range",
    "--magic-fix", "--bulk-validate",
    "--bulk-export-json", "--bulk-import-json",
    "--diff-tree", "--orphan-jsons", "--list-by-magic",
    "--catalog-stats",
    "--gen-animations", "--gen-animations-combat", "--gen-animations-movement",
    "--info-wani", "--validate-wani",
    "--export-wani-json", "--import-wani-json",
    "--gen-svk", "--gen-svk-combat", "--gen-svk-utility",
    "--info-wsvk", "--validate-wsvk",
    "--export-wsvk-json", "--import-wsvk-json",
    "--gen-wsui", "--gen-wsui-wintergrasp", "--gen-wsui-dungeon",
    "--info-wwui", "--validate-wwui",
    "--export-wwui-json", "--import-wwui-json",
    "--gen-pcn", "--gen-pcn-quest-gates", "--gen-pcn-composite",
    "--info-wpcn", "--validate-wpcn",
    "--export-wpcn-json", "--import-wpcn-json",
    "--gen-tsk", "--gen-tsk-blacksmithing", "--gen-tsk-alchemy",
    "--info-wtsk", "--validate-wtsk",
    "--export-wtsk-json", "--import-wtsk-json",
    "--gen-ceq", "--gen-ceq-bosses", "--gen-ceq-ranged",
    "--info-wceq", "--validate-wceq",
    "--export-wceq-json", "--import-wceq-json",
    "--gen-itset", "--gen-itset-tier", "--gen-itset-pvp",
    "--info-wset", "--validate-wset",
    "--export-wset-json", "--import-wset-json",
    "--gen-tips", "--gen-tips-new-player", "--gen-tips-advanced",
    "--info-wgtp", "--validate-wgtp",
    "--export-wgtp-json", "--import-wgtp-json",
    "--gen-cmp", "--gen-cmp-rare", "--gen-cmp-faction",
    "--info-wcmp", "--validate-wcmp",
    "--export-wcmp-json", "--import-wcmp-json",
    "--gen-smc", "--gen-smc-hard", "--gen-smc-roots",
    "--info-wsmc", "--validate-wsmc",
    "--export-wsmc-json", "--import-wsmc-json",
    "--gen-kbd", "--gen-kbd-movement", "--gen-kbd-ui",
    "--info-wkbd", "--validate-wkbd",
    "--export-wkbd-json", "--import-wkbd-json",
    "--gen-sch", "--gen-sch-magical", "--gen-sch-combined",
    "--info-wsch", "--validate-wsch",
    "--export-wsch-json", "--import-wsch-json",
    "--gen-lfg", "--gen-lfg-heroic", "--gen-lfg-raid",
    "--info-wlfg", "--validate-wlfg",
    "--export-wlfg-json", "--import-wlfg-json",
    "--gen-mac", "--gen-mac-combat", "--gen-mac-utility",
    "--info-wmac", "--validate-wmac",
    "--export-wmac-json", "--import-wmac-json",
    "--gen-chf", "--gen-chf-bloodelf", "--gen-chf-tauren",
    "--info-wchf", "--validate-wchf",
    "--export-wchf-json", "--import-wchf-json",
    "--gen-pvp", "--gen-pvp-alliance", "--gen-pvp-arena",
    "--info-wpvp", "--validate-wpvp",
    "--export-wpvp-json", "--import-wpvp-json",
    "--gen-bnk", "--gen-bnk-bank", "--gen-bnk-special",
    "--info-wbnk", "--validate-wbnk",
    "--export-wbnk-json", "--import-wbnk-json",
    "--gen-rune", "--gen-rune-blood", "--gen-rune-frost",
    "--info-wrun", "--validate-wrun",
    "--export-wrun-json", "--import-wrun-json",
    "--gen-lds", "--gen-lds-instances", "--gen-lds-raid",
    "--info-wlds", "--validate-wlds",
    "--export-wlds-json", "--import-wlds-json",
    "--gen-suf", "--gen-suf-magical", "--gen-suf-pvp",
    "--info-wsuf", "--validate-wsuf",
    "--export-wsuf-json", "--import-wsuf-json",
    "--gen-crr", "--gen-crr-defensive", "--gen-crr-spell",
    "--info-wcrr", "--validate-wcrr",
    "--export-wcrr-json", "--import-wcrr-json",
    "--gen-umv", "--gen-umv-flight", "--gen-umv-buffs",
    "--info-wumv", "--validate-wumv",
    "--export-wumv-json", "--import-wumv-json",
    "--gen-qso", "--gen-qso-class", "--gen-qso-profession",
    "--info-wqso", "--validate-wqso",
    "--export-wqso-json", "--import-wqso-json",
    "--gen-srg", "--gen-srg-ranged", "--gen-srg-friendly",
    "--info-wsrg", "--validate-wsrg",
    "--export-wsrg-json", "--import-wsrg-json",
    "--gen-sct", "--gen-sct-channel", "--gen-sct-ramp",
    "--info-wsct", "--validate-wsct",
    "--export-wsct-json", "--import-wsct-json",
    "--gen-sdr", "--gen-sdr-buffs", "--gen-sdr-dot",
    "--info-wsdr", "--validate-wsdr",
    "--export-wsdr-json", "--import-wsdr-json",
    "--gen-cdb", "--gen-cdb-class", "--gen-cdb-items",
    "--info-wscd", "--validate-wscd",
    "--export-wscd-json", "--import-wscd-json",
    "--gen-cef", "--gen-cef-ferocity", "--gen-cef-exotic",
    "--info-wcef", "--validate-wcef",
    "--export-wcef-json", "--import-wcef-json",
    "--gen-spc", "--gen-spc-rage", "--gen-spc-mixed",
    "--info-wspc", "--validate-wspc",
    "--export-wspc-json", "--import-wspc-json",
    "--gen-gfs", "--gen-gfs-wotlk", "--gen-gfs-cata",
    "--info-wgfs", "--validate-wgfs",
    "--export-wgfs-json", "--import-wgfs-json",
    "--gen-cdf", "--gen-cdf-wotlk-raid", "--gen-cdf-fiveman",
    "--info-wcdf", "--validate-wcdf",
    "--export-wcdf-json", "--import-wcdf-json",
    "--gen-mat", "--gen-mat-weapon", "--gen-mat-magical",
    "--info-wmat", "--validate-wmat",
    "--export-wmat-json", "--import-wmat-json",
    "--gen-psp", "--gen-psp-horde", "--gen-psp-dk",
    "--info-wpsp", "--validate-wpsp",
    "--export-wpsp-json", "--import-wpsp-json",
    "--gen-tle", "--gen-tle-mage", "--gen-tle-paladin",
    "--info-wtle", "--validate-wtle",
    "--export-wtle-json", "--import-wtle-json",
    "--gen-ctr", "--gen-ctr-pve", "--gen-ctr-faction",
    "--info-wctr", "--validate-wctr",
    "--export-wctr-json", "--import-wctr-json",
    "--gen-spr", "--gen-spr-warlock", "--gen-spr-rez",
    "--info-wspr", "--validate-wspr",
    "--export-wspr-json", "--import-wspr-json",
    "--gen-acr", "--gen-acr-quest", "--gen-acr-mixed",
    "--info-wacr", "--validate-wacr",
    "--export-wacr-json", "--import-wacr-json",
    "--gen-sef", "--gen-sef-healing", "--gen-sef-aura",
    "--info-wsef", "--validate-wsef",
    "--export-wsef-json", "--import-wsef-json",
    "--gen-aur", "--gen-aur-stats", "--gen-aur-movement",
    "--info-waur", "--validate-waur",
    "--export-waur-json", "--import-waur-json",
    "--gen-iqr", "--gen-iqr-server", "--gen-iqr-raid",
    "--info-wiqr", "--validate-wiqr",
    "--export-wiqr-json", "--import-wiqr-json",
    "--gen-scs", "--gen-scs-weapon", "--gen-scs-riding",
    "--info-wscs", "--validate-wscs",
    "--export-wscs-json", "--import-wscs-json",
    "--gen-ifs", "--gen-ifs-binding", "--gen-ifs-server",
    "--info-wifs", "--validate-wifs",
    "--export-wifs-json", "--import-wifs-json",
    "--gen-bkd", "--gen-bkd-battle", "--gen-bkd-profession",
    "--info-wbkd", "--validate-wbkd",
    "--export-wbkd-json", "--import-wbkd-json",
    "--gen-tbr", "--gen-tbr-pvp", "--gen-tbr-faction",
    "--info-wtbr", "--validate-wtbr",
    "--export-wtbr-json", "--import-wtbr-json",
    "--gen-sps", "--gen-sps-aura", "--gen-sps-talent",
    "--info-wsps", "--validate-wsps",
    "--export-wsps-json", "--import-wsps-json",
    "--gen-cmr", "--gen-cmr-city", "--gen-cmr-boss",
    "--info-wcmr", "--validate-wcmr",
    "--export-wcmr-json", "--import-wcmr-json",
    "--gen-bos", "--gen-bos-raid10", "--gen-bos-world",
    "--info-wbos", "--validate-wbos",
    "--export-wbos-json", "--import-wbos-json",
    "--gen-hld", "--gen-hld-dungeon", "--gen-hld-event",
    "--info-whld", "--validate-whld",
    "--export-whld-json", "--import-whld-json",
    "--gen-stc", "--gen-stc-cata", "--gen-stc-premium",
    "--info-wstc", "--validate-wstc",
    "--export-wstc-json", "--import-wstc-json",
    "--gen-stm", "--gen-stm-regen", "--gen-stm-armor",
    "--info-wstm", "--validate-wstm",
    "--export-wstm-json", "--import-wstm-json",
    "--gen-act", "--gen-act-mage", "--gen-act-pet",
    "--info-wact", "--validate-wact",
    "--export-wact-json", "--import-wact-json",
    "--gen-grp", "--gen-grp-raid10", "--gen-grp-raid25",
    "--info-wgrp", "--validate-wgrp",
    "--export-wgrp-json", "--import-wgrp-json",
    "--gen-hrt", "--gen-hrt-capitals", "--gen-hrt-inns",
    "--info-whrt", "--validate-whrt",
    "--export-whrt-json", "--import-whrt-json",
    "--gen-scb", "--gen-scb-maintenance", "--gen-scb-helptips",
    "--info-wscb", "--validate-wscb",
    "--export-wscb-json", "--import-wscb-json",
    "--gen-cmg", "--gen-cmg-druid", "--gen-cmg-all",
    "--info-wcmg", "--validate-wcmg",
    "--export-wcmg-json", "--import-wcmg-json",
    "--gen-msp", "--gen-msp-cluster", "--gen-msp-multi",
    "--info-wmsp", "--validate-wmsp",
    "--export-wmsp-json", "--import-wmsp-json",
    "--gen-emo", "--gen-emo-combat", "--gen-emo-rp",
    "--info-wemo", "--validate-wemo",
    "--export-wemo-json", "--import-wemo-json",
    "--gen-bab", "--gen-bab-druid", "--gen-bab-raid",
    "--info-wbab", "--validate-wbab",
    "--export-wbab-json", "--import-wbab-json",
    "--gen-tbd", "--gen-tbd-horde", "--gen-tbd-faction",
    "--info-wtbd", "--validate-wtbd",
    "--export-wtbd-json", "--import-wtbd-json",
    "--gen-spm", "--gen-spm-raid", "--gen-spm-env",
    "--info-wspm", "--validate-wspm",
    "--export-wspm-json", "--import-wspm-json",
    "--gen-ldn", "--gen-ldn-account", "--gen-ldn-rep",
    "--info-wldn", "--validate-wldn",
    "--export-wldn-json", "--import-wldn-json",
    "--gen-cre", "--gen-cre-elites", "--gen-cre-immune",
    "--info-wcre", "--validate-wcre",
    "--export-wcre-json", "--import-wcre-json",
    "--gen-ptt", "--gen-ptt-cunning", "--gen-ptt-tenacity",
    "--info-wptt", "--validate-wptt",
    "--export-wptt-json", "--import-wptt-json",
    "--gen-hrd", "--gen-hrd-raid25", "--gen-hrd-cm",
    "--info-whrd", "--validate-whrd",
    "--export-whrd-json", "--import-whrd-json",
    "--gen-rpr", "--gen-rpr-kaluak", "--gen-rpr-accord",
    "--info-wrpr", "--validate-wrpr",
    "--export-wrpr-json", "--import-wrpr-json",
    "--gen-mnl", "--gen-mnl-dalaran", "--gen-mnl-undercity",
    "--info-wmnl", "--validate-wmnl",
    "--export-wmnl-json", "--import-wmnl-json",
    "--gen-pcr", "--gen-pcr-stable", "--gen-pcr-warlock",
    "--info-wpcr", "--validate-wpcr",
    "--export-wpcr-json", "--import-wpcr-json",
    "--gen-mvc", "--gen-mvc-quest", "--gen-mvc-starter",
    "--info-wmvc", "--validate-wmvc",
    "--export-wmvc-json", "--import-wmvc-json",
    "--gen-spv", "--gen-spv-talent", "--gen-spv-racial",
    "--info-wspv", "--validate-wspv",
    "--export-wspv-json", "--import-wspv-json",
    "--gen-vox", "--gen-vox-boss", "--gen-vox-vendor",
    "--info-wvox", "--validate-wvox",
    "--export-wvox-json", "--import-wvox-json",
    "--gen-trd", "--gen-trd-admin", "--gen-trd-rmt",
    "--info-wtrd", "--validate-wtrd",
    "--export-wtrd-json", "--import-wtrd-json",
    "--gen-wfl", "--gen-wfl-caps", "--gen-wfl-url",
    "--info-wwfl", "--validate-wwfl",
    "--export-wwfl-json", "--import-wwfl-json",
    "--gen-mar", "--gen-mar-world", "--gen-mar-party",
    "--info-wmar", "--validate-wmar",
    "--export-wmar-json", "--import-wmar-json",
    "--gen-lma", "--gen-lma-raid", "--gen-lma-afk",
    "--info-wlma", "--validate-wlma",
    "--export-wlma-json", "--import-wlma-json",
    "--gen-skp", "--gen-skp-arctic", "--gen-skp-hellfire",
    "--info-wskp", "--validate-wskp",
    "--export-wskp-json", "--import-wskp-json",
    "--gen-cfg", "--gen-cfg-perf", "--gen-cfg-sec",
    "--info-wcfg", "--validate-wcfg",
    "--export-wcfg-json", "--import-wcfg-json",
    "--gen-anv", "--gen-anv-bonus", "--gen-anv-launch",
    "--info-wanv", "--validate-wanv",
    "--export-wanv-json", "--import-wanv-json",
    "--gen-prg", "--gen-prg-horde", "--gen-prg-high",
    "--info-wprg", "--validate-wprg",
    "--export-wprg-json", "--import-wprg-json",
    "--gen-lan", "--gen-lan-quest", "--gen-lan-tooltip",
    "--info-wlan", "--validate-wlan",
    "--export-wlan-json", "--import-wlan-json",
    "--gen-gch", "--gen-gch-rp", "--gen-gch-admin",
    "--info-wgch", "--validate-wgch",
    "--export-wgch-json", "--import-wgch-json",
    "--gen-mod", "--gen-mod-ui", "--gen-mod-util",
    "--info-wmod", "--validate-wmod",
    "--export-wmod-json", "--import-wmod-json",
    "--gen-spk-warrior", "--gen-spk-mage", "--gen-spk-rogue",
    "--info-wspk", "--validate-wspk",
    "--export-wspk-json", "--import-wspk-json",
    "--gen-phm-human", "--gen-phm-orc", "--gen-phm-undead",
    "--info-wphm", "--validate-wphm",
    "--export-wphm-json", "--import-wphm-json",
    "--gen-trn-zeppelins", "--gen-trn-boats", "--gen-trn-taxis",
    "--info-wtsc", "--validate-wtsc",
    "--export-wtsc-json", "--import-wtsc-json",
    "--gen-prt-alliance", "--gen-prt-horde", "--gen-prt-teleports",
    "--info-wprt", "--validate-wprt",
    "--export-wprt-json", "--import-wprt-json",
    "--gen-cst-warrior", "--gen-cst-mage", "--gen-cst-starting",
    "--info-wcst", "--validate-wcst",
    "--export-wcst-json", "--import-wcst-json",
    "--gen-gbk", "--gen-gbk-raid", "--gen-gbk-small",
    "--info-wgbk", "--validate-wgbk",
    "--export-wgbk-json", "--import-wgbk-json",
    "--gen-qgr-starter", "--gen-qgr-branched", "--gen-qgr-dailies",
    "--info-wqgr", "--validate-wqgr",
    "--export-wqgr-json", "--import-wqgr-json",
    "--gen-cra-alchemy", "--gen-cra-engineering", "--gen-cra-blacksmithing",
    "--info-wcra", "--validate-wcra",
    "--export-wcra-json", "--import-wcra-json",
    "--gen-loc-poi", "--gen-loc-herb", "--gen-loc-rare",
    "--info-wloc", "--validate-wloc",
    "--export-wloc-json", "--import-wloc-json",
    "--gen-bnd-vanilla", "--gen-bnd-tbc", "--gen-bnd-wotlk",
    "--info-wbnd", "--validate-wbnd",
    "--export-wbnd-json", "--import-wbnd-json",
    "--gen-bhv-melee", "--gen-bhv-caster", "--gen-bhv-boss",
    "--info-wbhv", "--validate-wbhv",
    "--export-wbhv-json", "--import-wbhv-json",
    "--gen-irc-bear", "--gen-irc-eagle", "--gen-irc-tiger",
    "--info-wirc", "--validate-wirc",
    "--export-wirc-json", "--import-wirc-json",
    "--gen-prc-weapon", "--gen-prc-ret", "--gen-prc-rage",
    "--info-wprc", "--validate-wprc",
    "--export-wprc-json", "--import-wprc-json",
    "--gen-auh-stormwind", "--gen-auh-orgrimmar", "--gen-auh-bootybay",
    "--info-wauh", "--validate-wauh",
    "--export-wauh-json", "--import-wauh-json",
    "--gen-brd-av", "--gen-brd-wsg", "--gen-brd-ab",
    "--info-wbrd", "--validate-wbrd",
    "--export-wbrd-json", "--import-wbrd-json",
    "--gen-swp-bosses", "--gen-swp-race", "--gen-swp-ui",
    "--info-wswp", "--validate-wswp",
    "--export-wswp-json", "--import-wswp-json",
    "--gen-tut-newbie", "--gen-tut-levelup", "--gen-tut-bg",
    "--info-wtur", "--validate-wtur",
    "--export-wtur-json", "--import-wtur-json",
    "--gen-cmd-basic", "--gen-cmd-movement", "--gen-cmd-admin",
    "--info-wcmd", "--validate-wcmd",
    "--export-wcmd-json", "--import-wcmd-json",
    "--gen-cam-combat", "--gen-cam-mounted", "--gen-cam-cinematic",
    "--info-wcam", "--validate-wcam",
    "--export-wcam-json", "--import-wcam-json",
    "--gen-cfr-warrior", "--gen-cfr-mage", "--gen-cfr-rogue",
    "--info-wcfr", "--validate-wcfr",
    "--export-wcfr-json", "--import-wcfr-json",
    "--gen-lnk-std", "--gen-lnk-talent", "--gen-lnk-quality",
    "--info-wlnk", "--validate-wlnk",
    "--export-wlnk-json", "--import-wlnk-json",
    "--gen-weather-temperate", "--gen-weather-arctic",
    "--gen-weather-desert", "--gen-weather-stormy",
    "--gen-zone-atmosphere",
    "--info-creatures", "--info-objects", "--info-quests",
    "--info-extract", "--info-extract-tree", "--info-extract-budget",
    "--list-missing-sidecars",
    "--info-png", "--info-jsondbc", "--info-blp", "--info-pack-budget",
    "--info-pack-tree",
    "--info-m2", "--info-wmo", "--info-adt",
    "--info-zone", "--info-zone-overview", "--info-project-overview",
    "--copy-project", "--info-wcp", "--list-wcp",
    "--list-creatures", "--list-objects", "--list-quests",
    "--list-quest-objectives", "--list-quest-rewards",
    "--info-creature", "--info-quest", "--info-object",
    "--info-quest-graph-stats",
    "--info-creatures-by-faction", "--info-creatures-by-level",
    "--info-objects-by-path", "--info-objects-by-type",
    "--info-quests-by-level", "--info-quests-by-xp",
    "--unpack-wcp", "--pack-wcp",
    "--validate", "--validate-wom", "--validate-wob", "--validate-woc",
    "--validate-whm", "--validate-all", "--validate-project",
    "--validate-project-open-only", "--audit-project", "--bench-audit-project",
    "--bench-validate-project", "--bench-bake-project",
    "--bench-migrate-data-tree", "--list-data-tree-largest",
    "--export-data-tree-md", "--gen-texture", "--gen-mesh", "--gen-mesh-textured",
    "--add-texture-to-mesh", "--add-texture-to-zone",
    "--gen-mesh-stairs", "--gen-mesh-grid", "--gen-mesh-disc",
    "--gen-mesh-tube", "--gen-mesh-capsule", "--gen-mesh-arch",
    "--gen-mesh-pyramid", "--gen-mesh-fence", "--gen-mesh-tree",
    "--gen-mesh-rock", "--gen-mesh-pillar", "--gen-mesh-bridge",
    "--gen-mesh-tower", "--gen-mesh-house", "--gen-mesh-fountain",
    "--gen-mesh-statue", "--gen-mesh-altar", "--gen-mesh-portal",
    "--gen-mesh-archway", "--gen-mesh-barrel", "--gen-mesh-chest",
    "--gen-mesh-anvil", "--gen-mesh-mushroom", "--gen-mesh-cart",
    "--gen-mesh-banner", "--gen-mesh-grave", "--gen-mesh-bench",
    "--gen-mesh-shrine", "--gen-mesh-totem", "--gen-mesh-cage",
    "--gen-mesh-throne", "--gen-mesh-coffin", "--gen-mesh-bookshelf",
    "--gen-mesh-tent", "--gen-mesh-firepit", "--gen-mesh-woodpile",
    "--gen-mesh-canopy", "--gen-mesh-haystack", "--gen-mesh-dock",
    "--gen-mesh-pergola", "--gen-mesh-chimney", "--gen-mesh-bedroll",
    "--gen-mesh-workbench", "--gen-mesh-crate-stack",
    "--gen-mesh-watchpost", "--gen-mesh-water-trough",
    "--gen-mesh-training-dummy", "--gen-mesh-hitching-post",
    "--gen-mesh-outhouse", "--gen-mesh-forge",
    "--gen-mesh-archery-target", "--gen-mesh-gravel-pile",
    "--gen-mesh-stone-bench", "--gen-mesh-mine-cart",
    "--gen-mesh-hitching-rail", "--gen-mesh-pillar-row",
    "--gen-mesh-statue-base", "--gen-mesh-bird-bath",
    "--gen-mesh-planter-box", "--gen-mesh-urn", "--gen-mesh-candle",
    "--gen-mesh-lantern", "--gen-mesh-chalice",
    "--gen-mesh-standing-torch", "--gen-mesh-scroll-case",
    "--gen-mesh-stove", "--gen-mesh-well-pail",
    "--gen-mesh-mug", "--gen-mesh-mortar-pestle",
    "--gen-mesh-rune-stone",
    "--gen-camp-pack", "--gen-blacksmith-pack", "--gen-village-pack",
    "--gen-temple-pack", "--gen-graveyard-pack",
    "--gen-garden-pack", "--gen-dock-pack", "--gen-tavern-pack",
    "--gen-mining-pack", "--gen-arena-pack",
    "--gen-kitchen-pack",
    "--gen-mesh-table", "--gen-mesh-lamppost", "--gen-mesh-bed",
    "--gen-mesh-ladder", "--gen-mesh-well", "--gen-mesh-signpost",
    "--gen-mesh-mailbox", "--gen-mesh-tombstone", "--gen-mesh-crate",
    "--gen-mesh-stool", "--gen-mesh-cauldron", "--gen-mesh-gate",
    "--gen-mesh-beehive", "--gen-mesh-weathervane",
    "--gen-mesh-scarecrow", "--gen-mesh-sundial",
    "--gen-mesh-podium", "--gen-mesh-brazier", "--gen-mesh-archway-double",
    "--gen-texture-gradient",
    "--gen-mesh-from-heightmap", "--export-mesh-heightmap",
    "--displace-mesh",
    "--scale-mesh", "--translate-mesh", "--strip-mesh",
    "--gen-texture-noise", "--gen-texture-noise-color", "--rotate-mesh",
    "--center-mesh", "--flip-mesh-normals", "--mirror-mesh",
    "--smooth-mesh-normals",
    "--merge-meshes",
    "--gen-texture-radial", "--gen-texture-stripes", "--gen-texture-dots",
    "--gen-texture-rings", "--gen-texture-checker", "--gen-texture-brick",
    "--gen-texture-wood", "--gen-texture-grass", "--gen-texture-fabric",
    "--gen-texture-cobble", "--gen-texture-marble", "--gen-texture-metal",
    "--gen-texture-leather", "--gen-texture-sand", "--gen-texture-snow",
    "--gen-texture-lava", "--gen-texture-tile", "--gen-texture-bark",
    "--gen-texture-clouds", "--gen-texture-stars", "--gen-texture-vines",
    "--gen-texture-mosaic", "--gen-texture-rust", "--gen-texture-circuit",
    "--gen-texture-coral", "--gen-texture-flame", "--gen-texture-tartan",
    "--gen-texture-argyle", "--gen-texture-herringbone",
    "--gen-texture-scales", "--gen-texture-stained-glass",
    "--gen-texture-shingles", "--gen-texture-frost",
    "--gen-texture-parquet", "--gen-texture-bubbles",
    "--gen-texture-spider-web", "--gen-texture-gingham",
    "--gen-texture-lattice", "--gen-texture-honeycomb",
    "--gen-texture-cracked", "--gen-texture-runes",
    "--gen-texture-leopard", "--gen-texture-zebra",
    "--gen-texture-knit", "--gen-texture-chainmail",
    "--gen-texture-planks", "--gen-texture-corrugated",
    "--gen-texture-rope", "--gen-texture-caustics",
    "--gen-texture-starburst", "--gen-texture-studs",
    "--gen-texture-moss", "--gen-texture-woodgrain",
    "--gen-texture-carbon", "--gen-texture-pinstripe",
    "--gen-texture-camo", "--gen-texture-snake-skin",
    "--gen-texture-mesh-screen", "--gen-texture-bamboo",
    "--gen-texture-blueprint", "--gen-texture-rust-streaks",
    "--gen-texture-plaid", "--gen-texture-diamond-grid",
    "--gen-texture-houndstooth", "--gen-texture-chevron",
    "--gen-texture-dunes", "--gen-texture-swirl",
    "--gen-texture-ironbark", "--gen-texture-mold",
    "--gen-texture-embroidery", "--gen-texture-lightbeam",
    "--gen-texture-dewdrops", "--gen-texture-pinwheel",
    "--gen-texture-scratched-metal", "--gen-texture-crackle",
    "--gen-texture-star", "--gen-texture-halftone",
    "--gen-texture-bayer", "--gen-texture-moon",
    "--gen-texture-damask", "--gen-texture-snowflake",
    "--gen-texture-gear-cog",
    "--validate-glb", "--info-glb", "--info-glb-tree", "--info-glb-bytes",
    "--validate-jsondbc", "--check-glb-bounds", "--validate-stl",
    "--validate-png", "--validate-blp",
    "--zone-summary", "--info-zone-tree", "--info-project-tree",
    "--info-zone-bytes", "--info-project-bytes",
    "--info-zone-extents", "--info-project-extents",
    "--info-zone-water", "--info-project-water",
    "--info-zone-density", "--info-project-density",
    "--export-zone-summary-md", "--export-quest-graph",
    "--export-zone-csv", "--export-zone-html", "--export-project-html",
    "--export-project-md", "--export-zone-checksum", "--export-project-checksum",
    "--validate-project-checksum",
    "--scaffold-zone", "--mvp-zone", "--add-tile", "--remove-tile", "--list-tiles",
    "--for-each-zone", "--for-each-tile", "--zone-stats", "--info-tilemap",
    "--list-zone-deps", "--list-project-orphans", "--remove-project-orphans",
    "--check-zone-refs", "--check-zone-content",
    "--check-project-content", "--check-project-refs",
    "--export-zone-deps-md", "--export-zone-spawn-png",
    "--add-creature", "--add-object", "--add-quest", "--add-item",
    "--random-populate-zone", "--random-populate-items",
    "--info-zone-audio", "--snap-zone-to-ground", "--audit-zone-spawns",
    "--info-project-audio", "--snap-project-to-ground",
    "--audit-project-spawns", "--list-zone-spawns", "--list-project-spawns",
    "--gen-random-zone", "--gen-random-project", "--gen-zone-texture-pack",
    "--gen-zone-mesh-pack", "--gen-zone-starter-pack",
    "--gen-project-starter-pack", "--gen-audio-tone",
    "--gen-audio-noise", "--gen-audio-sweep", "--gen-zone-audio-pack",
    "--info-zone-summary", "--info-project-summary",
    "--info-zone-deps", "--info-project-deps",
    "--gen-zone-readme", "--gen-project-readme",
    "--validate-zone-pack", "--validate-project-packs", "--info-spawn",
    "--diff-zone-spawns",
    "--list-items", "--info-item", "--set-item", "--export-zone-items-md",
    "--export-project-items-md", "--export-project-items-csv",
    "--add-quest-objective", "--add-quest-reward-item", "--set-quest-reward",
    "--remove-quest-objective", "--clone-quest", "--clone-creature",
    "--clone-item", "--validate-items", "--validate-project-items",
    "--info-project-items",
    "--clone-object",
    "--remove-creature", "--remove-object", "--remove-quest", "--remove-item",
    "--copy-zone-items",
    "--copy-zone", "--rename-zone", "--remove-zone",
    "--clear-zone-content", "--strip-zone", "--strip-project",
    "--repair-zone", "--repair-project",
    "--gen-makefile", "--gen-project-makefile",
    "--build-woc", "--regen-collision", "--fix-zone",
    "--export-png", "--export-obj", "--import-obj",
    "--export-wob-obj", "--import-wob-obj",
    "--export-woc-obj", "--export-whm-obj",
    "--export-glb", "--export-wob-glb", "--export-whm-glb",
    "--export-stl", "--import-stl",
    "--bake-zone-glb", "--bake-zone-stl", "--bake-zone-obj",
    "--bake-project-obj", "--bake-project-stl", "--bake-project-glb",
    "--bake-wom-collision", "--bake-wob-collision", "--bake-zone-collision",
    "--audit-watertight", "--audit-watertight-wob",
    "--convert-m2", "--convert-m2-batch",
    "--convert-wmo", "--convert-wmo-batch",
    "--convert-dbc-json", "--convert-dbc-batch", "--convert-json-dbc",
    "--convert-blp-png", "--convert-blp-batch",
    "--migrate-wom", "--migrate-zone", "--migrate-project",
    "--migrate-data-tree", "--info-data-tree", "--strip-data-tree",
    "--audit-data-tree",
    "--migrate-jsondbc",
};

const std::size_t kArgRequiredSize =
    sizeof(kArgRequired) / sizeof(kArgRequired[0]);

} // namespace cli
} // namespace editor
} // namespace wowee
