// ============================================================================
// animation_ids.cpp - Inverse lookup & DBC validation
// Generated from animation_ids.hpp (452 constants, IDs 0–451)
// ============================================================================
#include "rendering/animation/animation_ids.hpp"
#include "pipeline/dbc_loader.hpp"
#include "core/logger.hpp"

#include <unordered_set>

namespace wowee {
namespace rendering {
namespace anim {

const char* nameFromId(uint32_t id) {
    static const char* const names[ANIM_COUNT] = {
        /*   0 */ "STAND",
        /*   1 */ "DEATH",
        /*   2 */ "SPELL",
        /*   3 */ "STOP",
        /*   4 */ "WALK",
        /*   5 */ "RUN",
        /*   6 */ "DEAD",
        /*   7 */ "RISE",
        /*   8 */ "STAND_WOUND",
        /*   9 */ "COMBAT_WOUND",
        /*  10 */ "COMBAT_CRITICAL",
        /*  11 */ "SHUFFLE_LEFT",
        /*  12 */ "SHUFFLE_RIGHT",
        /*  13 */ "WALK_BACKWARDS",
        /*  14 */ "STUN",
        /*  15 */ "HANDS_CLOSED",
        /*  16 */ "ATTACK_UNARMED",
        /*  17 */ "ATTACK_1H",
        /*  18 */ "ATTACK_2H",
        /*  19 */ "ATTACK_2H_LOOSE",
        /*  20 */ "PARRY_UNARMED",
        /*  21 */ "PARRY_1H",
        /*  22 */ "PARRY_2H",
        /*  23 */ "PARRY_2H_LOOSE",
        /*  24 */ "SHIELD_BLOCK",
        /*  25 */ "READY_UNARMED",
        /*  26 */ "READY_1H",
        /*  27 */ "READY_2H",
        /*  28 */ "READY_2H_LOOSE",
        /*  29 */ "READY_BOW",
        /*  30 */ "DODGE",
        /*  31 */ "SPELL_PRECAST",
        /*  32 */ "SPELL_CAST",
        /*  33 */ "SPELL_CAST_AREA",
        /*  34 */ "NPC_WELCOME",
        /*  35 */ "NPC_GOODBYE",
        /*  36 */ "BLOCK",
        /*  37 */ "JUMP_START",
        /*  38 */ "JUMP",
        /*  39 */ "JUMP_END",
        /*  40 */ "FALL",
        /*  41 */ "SWIM_IDLE",
        /*  42 */ "SWIM",
        /*  43 */ "SWIM_LEFT",
        /*  44 */ "SWIM_RIGHT",
        /*  45 */ "SWIM_BACKWARDS",
        /*  46 */ "ATTACK_BOW",
        /*  47 */ "FIRE_BOW",
        /*  48 */ "READY_RIFLE",
        /*  49 */ "ATTACK_RIFLE",
        /*  50 */ "LOOT",
        /*  51 */ "READY_SPELL_DIRECTED",
        /*  52 */ "READY_SPELL_OMNI",
        /*  53 */ "SPELL_CAST_DIRECTED",
        /*  54 */ "SPELL_CAST_OMNI",
        /*  55 */ "BATTLE_ROAR",
        /*  56 */ "READY_ABILITY",
        /*  57 */ "SPECIAL_1H",
        /*  58 */ "SPECIAL_2H",
        /*  59 */ "SHIELD_BASH",
        /*  60 */ "EMOTE_TALK",
        /*  61 */ "EMOTE_EAT",
        /*  62 */ "EMOTE_WORK",
        /*  63 */ "EMOTE_USE_STANDING",
        /*  64 */ "EMOTE_EXCLAMATION",
        /*  65 */ "EMOTE_QUESTION",
        /*  66 */ "EMOTE_BOW",
        /*  67 */ "EMOTE_WAVE",
        /*  68 */ "EMOTE_CHEER",
        /*  69 */ "EMOTE_DANCE",
        /*  70 */ "EMOTE_LAUGH",
        /*  71 */ "EMOTE_SLEEP",
        /*  72 */ "EMOTE_SIT_GROUND",
        /*  73 */ "EMOTE_RUDE",
        /*  74 */ "EMOTE_ROAR",
        /*  75 */ "EMOTE_KNEEL",
        /*  76 */ "EMOTE_KISS",
        /*  77 */ "EMOTE_CRY",
        /*  78 */ "EMOTE_CHICKEN",
        /*  79 */ "EMOTE_BEG",
        /*  80 */ "EMOTE_APPLAUD",
        /*  81 */ "EMOTE_SHOUT",
        /*  82 */ "EMOTE_FLEX",
        /*  83 */ "EMOTE_SHY",
        /*  84 */ "EMOTE_POINT",
        /*  85 */ "ATTACK_1H_PIERCE",
        /*  86 */ "ATTACK_2H_LOOSE_PIERCE",
        /*  87 */ "ATTACK_OFF",
        /*  88 */ "ATTACK_OFF_PIERCE",
        /*  89 */ "SHEATHE",
        /*  90 */ "HIP_SHEATHE",
        /*  91 */ "MOUNT",
        /*  92 */ "RUN_RIGHT",
        /*  93 */ "RUN_LEFT",
        /*  94 */ "MOUNT_SPECIAL",
        /*  95 */ "KICK",
        /*  96 */ "SIT_GROUND_DOWN",
        /*  97 */ "SITTING",
        /*  98 */ "SIT_GROUND_UP",
        /*  99 */ "SLEEP_DOWN",
        /* 100 */ "SLEEP",
        /* 101 */ "SLEEP_UP",
        /* 102 */ "SIT_CHAIR_LOW",
        /* 103 */ "SIT_CHAIR_MED",
        /* 104 */ "SIT_CHAIR_HIGH",
        /* 105 */ "LOAD_BOW",
        /* 106 */ "LOAD_RIFLE",
        /* 107 */ "ATTACK_THROWN",
        /* 108 */ "READY_THROWN",
        /* 109 */ "HOLD_BOW",
        /* 110 */ "HOLD_RIFLE",
        /* 111 */ "HOLD_THROWN",
        /* 112 */ "LOAD_THROWN",
        /* 113 */ "EMOTE_SALUTE",
        /* 114 */ "KNEEL_START",
        /* 115 */ "KNEEL_LOOP",
        /* 116 */ "KNEEL_END",
        /* 117 */ "ATTACK_UNARMED_OFF",
        /* 118 */ "SPECIAL_UNARMED",
        /* 119 */ "STEALTH_WALK",
        /* 120 */ "STEALTH_STAND",
        /* 121 */ "KNOCKDOWN",
        /* 122 */ "EATING_LOOP",
        /* 123 */ "USE_STANDING_LOOP",
        /* 124 */ "CHANNEL_CAST_DIRECTED",
        /* 125 */ "CHANNEL_CAST_OMNI",
        /* 126 */ "WHIRLWIND",
        /* 127 */ "BIRTH",
        /* 128 */ "USE_STANDING_START",
        /* 129 */ "USE_STANDING_END",
        /* 130 */ "CREATURE_SPECIAL",
        /* 131 */ "DROWN",
        /* 132 */ "DROWNED",
        /* 133 */ "FISHING_CAST",
        /* 134 */ "FISHING_LOOP",
        /* 135 */ "FLY",
        /* 136 */ "EMOTE_WORK_NO_SHEATHE",
        /* 137 */ "EMOTE_STUN_NO_SHEATHE",
        /* 138 */ "EMOTE_USE_STANDING_NO_SHEATHE",
        /* 139 */ "SPELL_SLEEP_DOWN",
        /* 140 */ "SPELL_KNEEL_START",
        /* 141 */ "SPELL_KNEEL_LOOP",
        /* 142 */ "SPELL_KNEEL_END",
        /* 143 */ "SPRINT",
        /* 144 */ "IN_FLIGHT",
        /* 145 */ "SPAWN",
        /* 146 */ "CLOSE",
        /* 147 */ "CLOSED",
        /* 148 */ "OPEN",
        /* 149 */ "OPENED",
        /* 150 */ "DESTROY",
        /* 151 */ "DESTROYED",
        /* 152 */ "REBUILD",
        /* 153 */ "CUSTOM_0",
        /* 154 */ "CUSTOM_1",
        /* 155 */ "CUSTOM_2",
        /* 156 */ "CUSTOM_3",
        /* 157 */ "DESPAWN",
        /* 158 */ "HOLD",
        /* 159 */ "DECAY",
        /* 160 */ "BOW_PULL",
        /* 161 */ "BOW_RELEASE",
        /* 162 */ "SHIP_START",
        /* 163 */ "SHIP_MOVING",
        /* 164 */ "SHIP_STOP",
        /* 165 */ "GROUP_ARROW",
        /* 166 */ "ARROW",
        /* 167 */ "CORPSE_ARROW",
        /* 168 */ "GUIDE_ARROW",
        /* 169 */ "SWAY",
        /* 170 */ "DRUID_CAT_POUNCE",
        /* 171 */ "DRUID_CAT_RIP",
        /* 172 */ "DRUID_CAT_RAKE",
        /* 173 */ "DRUID_CAT_RAVAGE",
        /* 174 */ "DRUID_CAT_CLAW",
        /* 175 */ "DRUID_CAT_COWER",
        /* 176 */ "DRUID_BEAR_SWIPE",
        /* 177 */ "DRUID_BEAR_BITE",
        /* 178 */ "DRUID_BEAR_MAUL",
        /* 179 */ "DRUID_BEAR_BASH",
        /* 180 */ "DRAGON_TAIL",
        /* 181 */ "DRAGON_STOMP",
        /* 182 */ "DRAGON_SPIT",
        /* 183 */ "DRAGON_SPIT_HOVER",
        /* 184 */ "DRAGON_SPIT_FLY",
        /* 185 */ "EMOTE_YES",
        /* 186 */ "EMOTE_NO",
        /* 187 */ "JUMP_LAND_RUN",
        /* 188 */ "LOOT_HOLD",
        /* 189 */ "LOOT_UP",
        /* 190 */ "STAND_HIGH",
        /* 191 */ "IMPACT",
        /* 192 */ "LIFT_OFF",
        /* 193 */ "HOVER",
        /* 194 */ "SUCCUBUS_ENTICE",
        /* 195 */ "EMOTE_TRAIN",
        /* 196 */ "EMOTE_DEAD",
        /* 197 */ "EMOTE_DANCE_ONCE",
        /* 198 */ "DEFLECT",
        /* 199 */ "EMOTE_EAT_NO_SHEATHE",
        /* 200 */ "LAND",
        /* 201 */ "SUBMERGE",
        /* 202 */ "SUBMERGED",
        /* 203 */ "CANNIBALIZE",
        /* 204 */ "ARROW_BIRTH",
        /* 205 */ "GROUP_ARROW_BIRTH",
        /* 206 */ "CORPSE_ARROW_BIRTH",
        /* 207 */ "GUIDE_ARROW_BIRTH",
        /* 208 */ "EMOTE_TALK_NO_SHEATHE",
        /* 209 */ "EMOTE_POINT_NO_SHEATHE",
        /* 210 */ "EMOTE_SALUTE_NO_SHEATHE",
        /* 211 */ "EMOTE_DANCE_SPECIAL",
        /* 212 */ "MUTILATE",
        /* 213 */ "CUSTOM_SPELL_01",
        /* 214 */ "CUSTOM_SPELL_02",
        /* 215 */ "CUSTOM_SPELL_03",
        /* 216 */ "CUSTOM_SPELL_04",
        /* 217 */ "CUSTOM_SPELL_05",
        /* 218 */ "CUSTOM_SPELL_06",
        /* 219 */ "CUSTOM_SPELL_07",
        /* 220 */ "CUSTOM_SPELL_08",
        /* 221 */ "CUSTOM_SPELL_09",
        /* 222 */ "CUSTOM_SPELL_10",
        /* 223 */ "STEALTH_RUN",
        /* 224 */ "EMERGE",
        /* 225 */ "COWER",
        /* 226 */ "GRAB",
        /* 227 */ "GRAB_CLOSED",
        /* 228 */ "GRAB_THROWN",
        /* 229 */ "FLY_STAND",
        /* 230 */ "FLY_DEATH",
        /* 231 */ "FLY_SPELL",
        /* 232 */ "FLY_STOP",
        /* 233 */ "FLY_WALK",
        /* 234 */ "FLY_RUN",
        /* 235 */ "FLY_DEAD",
        /* 236 */ "FLY_RISE",
        /* 237 */ "FLY_STAND_WOUND",
        /* 238 */ "FLY_COMBAT_WOUND",
        /* 239 */ "FLY_COMBAT_CRITICAL",
        /* 240 */ "FLY_SHUFFLE_LEFT",
        /* 241 */ "FLY_SHUFFLE_RIGHT",
        /* 242 */ "FLY_WALKBACKWARDS",
        /* 243 */ "FLY_STUN",
        /* 244 */ "FLY_HANDS_CLOSED",
        /* 245 */ "FLY_ATTACK_UNARMED",
        /* 246 */ "FLY_ATTACK_1H",
        /* 247 */ "FLY_ATTACK_2H",
        /* 248 */ "FLY_ATTACK_2HL",
        /* 249 */ "FLY_PARRY_UNARMED",
        /* 250 */ "FLY_PARRY_1H",
        /* 251 */ "FLY_PARRY_2H",
        /* 252 */ "FLY_PARRY_2HL",
        /* 253 */ "FLY_SHIELD_BLOCK",
        /* 254 */ "FLY_READY_UNARMED",
        /* 255 */ "FLY_READY_1H",
        /* 256 */ "FLY_READY_2H",
        /* 257 */ "FLY_READY_2HL",
        /* 258 */ "FLY_READY_BOW",
        /* 259 */ "FLY_DODGE",
        /* 260 */ "FLY_SPELL_PRECAST",
        /* 261 */ "FLY_SPELL_CAST",
        /* 262 */ "FLY_SPELL_CAST_AREA",
        /* 263 */ "FLY_NPC_WELCOME",
        /* 264 */ "FLY_NPC_GOODBYE",
        /* 265 */ "FLY_BLOCK",
        /* 266 */ "FLY_JUMP_START",
        /* 267 */ "FLY_JUMP",
        /* 268 */ "FLY_JUMP_END",
        /* 269 */ "FLY_FALL",
        /* 270 */ "FLY_SWIM_IDLE",
        /* 271 */ "FLY_SWIM",
        /* 272 */ "FLY_SWIM_LEFT",
        /* 273 */ "FLY_SWIM_RIGHT",
        /* 274 */ "FLY_SWIM_BACKWARDS",
        /* 275 */ "FLY_ATTACK_BOW",
        /* 276 */ "FLY_FIRE_BOW",
        /* 277 */ "FLY_READY_RIFLE",
        /* 278 */ "FLY_ATTACK_RIFLE",
        /* 279 */ "FLY_LOOT",
        /* 280 */ "FLY_READY_SPELL_DIRECTED",
        /* 281 */ "FLY_READY_SPELL_OMNI",
        /* 282 */ "FLY_SPELL_CAST_DIRECTED",
        /* 283 */ "FLY_SPELL_CAST_OMNI",
        /* 284 */ "FLY_BATTLE_ROAR",
        /* 285 */ "FLY_READY_ABILITY",
        /* 286 */ "FLY_SPECIAL_1H",
        /* 287 */ "FLY_SPECIAL_2H",
        /* 288 */ "FLY_SHIELD_BASH",
        /* 289 */ "FLY_EMOTE_TALK",
        /* 290 */ "FLY_EMOTE_EAT",
        /* 291 */ "FLY_EMOTE_WORK",
        /* 292 */ "FLY_EMOTE_USE_STANDING",
        /* 293 */ "FLY_EMOTE_TALK_EXCLAMATION",
        /* 294 */ "FLY_EMOTE_TALK_QUESTION",
        /* 295 */ "FLY_EMOTE_BOW",
        /* 296 */ "FLY_EMOTE_WAVE",
        /* 297 */ "FLY_EMOTE_CHEER",
        /* 298 */ "FLY_EMOTE_DANCE",
        /* 299 */ "FLY_EMOTE_LAUGH",
        /* 300 */ "FLY_EMOTE_SLEEP",
        /* 301 */ "FLY_EMOTE_SIT_GROUND",
        /* 302 */ "FLY_EMOTE_RUDE",
        /* 303 */ "FLY_EMOTE_ROAR",
        /* 304 */ "FLY_EMOTE_KNEEL",
        /* 305 */ "FLY_EMOTE_KISS",
        /* 306 */ "FLY_EMOTE_CRY",
        /* 307 */ "FLY_EMOTE_CHICKEN",
        /* 308 */ "FLY_EMOTE_BEG",
        /* 309 */ "FLY_EMOTE_APPLAUD",
        /* 310 */ "FLY_EMOTE_SHOUT",
        /* 311 */ "FLY_EMOTE_FLEX",
        /* 312 */ "FLY_EMOTE_SHY",
        /* 313 */ "FLY_EMOTE_POINT",
        /* 314 */ "FLY_ATTACK_1H_PIERCE",
        /* 315 */ "FLY_ATTACK_2H_LOOSE_PIERCE",
        /* 316 */ "FLY_ATTACK_OFF",
        /* 317 */ "FLY_ATTACK_OFF_PIERCE",
        /* 318 */ "FLY_SHEATH",
        /* 319 */ "FLY_HIP_SHEATH",
        /* 320 */ "FLY_MOUNT",
        /* 321 */ "FLY_RUN_RIGHT",
        /* 322 */ "FLY_RUN_LEFT",
        /* 323 */ "FLY_MOUNT_SPECIAL",
        /* 324 */ "FLY_KICK",
        /* 325 */ "FLY_SIT_GROUND_DOWN",
        /* 326 */ "FLY_SIT_GROUND",
        /* 327 */ "FLY_SIT_GROUND_UP",
        /* 328 */ "FLY_SLEEP_DOWN",
        /* 329 */ "FLY_SLEEP",
        /* 330 */ "FLY_SLEEP_UP",
        /* 331 */ "FLY_SIT_CHAIR_LOW",
        /* 332 */ "FLY_SIT_CHAIR_MED",
        /* 333 */ "FLY_SIT_CHAIR_HIGH",
        /* 334 */ "FLY_LOAD_BOW",
        /* 335 */ "FLY_LOAD_RIFLE",
        /* 336 */ "FLY_ATTACK_THROWN",
        /* 337 */ "FLY_READY_THROWN",
        /* 338 */ "FLY_HOLD_BOW",
        /* 339 */ "FLY_HOLD_RIFLE",
        /* 340 */ "FLY_HOLD_THROWN",
        /* 341 */ "FLY_LOAD_THROWN",
        /* 342 */ "FLY_EMOTE_SALUTE",
        /* 343 */ "FLY_KNEEL_START",
        /* 344 */ "FLY_KNEEL_LOOP",
        /* 345 */ "FLY_KNEEL_END",
        /* 346 */ "FLY_ATTACK_UNARMED_OFF",
        /* 347 */ "FLY_SPECIAL_UNARMED",
        /* 348 */ "FLY_STEALTH_WALK",
        /* 349 */ "FLY_STEALTH_STAND",
        /* 350 */ "FLY_KNOCKDOWN",
        /* 351 */ "FLY_EATING_LOOP",
        /* 352 */ "FLY_USE_STANDING_LOOP",
        /* 353 */ "FLY_CHANNEL_CAST_DIRECTED",
        /* 354 */ "FLY_CHANNEL_CAST_OMNI",
        /* 355 */ "FLY_WHIRLWIND",
        /* 356 */ "FLY_BIRTH",
        /* 357 */ "FLY_USE_STANDING_START",
        /* 358 */ "FLY_USE_STANDING_END",
        /* 359 */ "FLY_CREATURE_SPECIAL",
        /* 360 */ "FLY_DROWN",
        /* 361 */ "FLY_DROWNED",
        /* 362 */ "FLY_FISHING_CAST",
        /* 363 */ "FLY_FISHING_LOOP",
        /* 364 */ "FLY_FLY",
        /* 365 */ "FLY_EMOTE_WORK_NO_SHEATHE",
        /* 366 */ "FLY_EMOTE_STUN_NO_SHEATHE",
        /* 367 */ "FLY_EMOTE_USE_STANDING_NO_SHEATHE",
        /* 368 */ "FLY_SPELL_SLEEP_DOWN",
        /* 369 */ "FLY_SPELL_KNEEL_START",
        /* 370 */ "FLY_SPELL_KNEEL_LOOP",
        /* 371 */ "FLY_SPELL_KNEEL_END",
        /* 372 */ "FLY_SPRINT",
        /* 373 */ "FLY_IN_FLIGHT",
        /* 374 */ "FLY_SPAWN",
        /* 375 */ "FLY_CLOSE",
        /* 376 */ "FLY_CLOSED",
        /* 377 */ "FLY_OPEN",
        /* 378 */ "FLY_OPENED",
        /* 379 */ "FLY_DESTROY",
        /* 380 */ "FLY_DESTROYED",
        /* 381 */ "FLY_REBUILD",
        /* 382 */ "FLY_CUSTOM_0",
        /* 383 */ "FLY_CUSTOM_1",
        /* 384 */ "FLY_CUSTOM_2",
        /* 385 */ "FLY_CUSTOM_3",
        /* 386 */ "FLY_DESPAWN",
        /* 387 */ "FLY_HOLD",
        /* 388 */ "FLY_DECAY",
        /* 389 */ "FLY_BOW_PULL",
        /* 390 */ "FLY_BOW_RELEASE",
        /* 391 */ "FLY_SHIP_START",
        /* 392 */ "FLY_SHIP_MOVING",
        /* 393 */ "FLY_SHIP_STOP",
        /* 394 */ "FLY_GROUP_ARROW",
        /* 395 */ "FLY_ARROW",
        /* 396 */ "FLY_CORPSE_ARROW",
        /* 397 */ "FLY_GUIDE_ARROW",
        /* 398 */ "FLY_SWAY",
        /* 399 */ "FLY_DRUID_CAT_POUNCE",
        /* 400 */ "FLY_DRUID_CAT_RIP",
        /* 401 */ "FLY_DRUID_CAT_RAKE",
        /* 402 */ "FLY_DRUID_CAT_RAVAGE",
        /* 403 */ "FLY_DRUID_CAT_CLAW",
        /* 404 */ "FLY_DRUID_CAT_COWER",
        /* 405 */ "FLY_DRUID_BEAR_SWIPE",
        /* 406 */ "FLY_DRUID_BEAR_BITE",
        /* 407 */ "FLY_DRUID_BEAR_MAUL",
        /* 408 */ "FLY_DRUID_BEAR_BASH",
        /* 409 */ "FLY_DRAGON_TAIL",
        /* 410 */ "FLY_DRAGON_STOMP",
        /* 411 */ "FLY_DRAGON_SPIT",
        /* 412 */ "FLY_DRAGON_SPIT_HOVER",
        /* 413 */ "FLY_DRAGON_SPIT_FLY",
        /* 414 */ "FLY_EMOTE_YES",
        /* 415 */ "FLY_EMOTE_NO",
        /* 416 */ "FLY_JUMP_LAND_RUN",
        /* 417 */ "FLY_LOOT_HOLD",
        /* 418 */ "FLY_LOOT_UP",
        /* 419 */ "FLY_STAND_HIGH",
        /* 420 */ "FLY_IMPACT",
        /* 421 */ "FLY_LIFT_OFF",
        /* 422 */ "FLY_HOVER",
        /* 423 */ "FLY_SUCCUBUS_ENTICE",
        /* 424 */ "FLY_EMOTE_TRAIN",
        /* 425 */ "FLY_EMOTE_DEAD",
        /* 426 */ "FLY_EMOTE_DANCE_ONCE",
        /* 427 */ "FLY_DEFLECT",
        /* 428 */ "FLY_EMOTE_EAT_NO_SHEATHE",
        /* 429 */ "FLY_LAND",
        /* 430 */ "FLY_SUBMERGE",
        /* 431 */ "FLY_SUBMERGED",
        /* 432 */ "FLY_CANNIBALIZE",
        /* 433 */ "FLY_ARROW_BIRTH",
        /* 434 */ "FLY_GROUP_ARROW_BIRTH",
        /* 435 */ "FLY_CORPSE_ARROW_BIRTH",
        /* 436 */ "FLY_GUIDE_ARROW_BIRTH",
        /* 437 */ "FLY_EMOTE_TALK_NO_SHEATHE",
        /* 438 */ "FLY_EMOTE_POINT_NO_SHEATHE",
        /* 439 */ "FLY_EMOTE_SALUTE_NO_SHEATHE",
        /* 440 */ "FLY_EMOTE_DANCE_SPECIAL",
        /* 441 */ "FLY_MUTILATE",
        /* 442 */ "FLY_CUSTOM_SPELL_01",
        /* 443 */ "FLY_CUSTOM_SPELL_02",
        /* 444 */ "FLY_CUSTOM_SPELL_03",
        /* 445 */ "FLY_CUSTOM_SPELL_04",
        /* 446 */ "FLY_CUSTOM_SPELL_05",
        /* 447 */ "FLY_CUSTOM_SPELL_06",
        /* 448 */ "FLY_CUSTOM_SPELL_07",
        /* 449 */ "FLY_CUSTOM_SPELL_08",
        /* 450 */ "FLY_CUSTOM_SPELL_09",
        /* 451 */ "FLY_CUSTOM_SPELL_10",
        /* 452 */ "FLY_STEALTH_RUN",
        /* 453 */ "FLY_EMERGE",
        /* 454 */ "FLY_COWER",
        /* 455 */ "FLY_GRAB",
        /* 456 */ "FLY_GRAB_CLOSED",
        /* 457 */ "FLY_GRAB_THROWN",
        /* 458 */ "TO_FLY",
        /* 459 */ "TO_HOVER",
        /* 460 */ "TO_GROUND",
        /* 461 */ "FLY_TO_FLY",
        /* 462 */ "FLY_TO_HOVER",
        /* 463 */ "FLY_TO_GROUND",
        /* 464 */ "SETTLE",
        /* 465 */ "FLY_SETTLE",
        /* 466 */ "DEATH_START",
        /* 467 */ "DEATH_LOOP",
        /* 468 */ "DEATH_END",
        /* 469 */ "FLY_DEATH_START",
        /* 470 */ "FLY_DEATH_LOOP",
        /* 471 */ "FLY_DEATH_END",
        /* 472 */ "DEATH_END_HOLD",
        /* 473 */ "FLY_DEATH_END_HOLD",
        /* 474 */ "STRANGULATE",
        /* 475 */ "FLY_STRANGULATE",
        /* 476 */ "READY_JOUST",
        /* 477 */ "LOAD_JOUST",
        /* 478 */ "HOLD_JOUST",
        /* 479 */ "FLY_READY_JOUST",
        /* 480 */ "FLY_LOAD_JOUST",
        /* 481 */ "FLY_HOLD_JOUST",
        /* 482 */ "ATTACK_JOUST",
        /* 483 */ "FLY_ATTACK_JOUST",
        /* 484 */ "RECLINED_MOUNT",
        /* 485 */ "FLY_RECLINED_MOUNT",
        /* 486 */ "TO_ALTERED",
        /* 487 */ "FROM_ALTERED",
        /* 488 */ "FLY_TO_ALTERED",
        /* 489 */ "FLY_FROM_ALTERED",
        /* 490 */ "IN_STOCKS",
        /* 491 */ "FLY_IN_STOCKS",
        /* 492 */ "VEHICLE_GRAB",
        /* 493 */ "VEHICLE_THROW",
        /* 494 */ "FLY_VEHICLE_GRAB",
        /* 495 */ "FLY_VEHICLE_THROW",
        /* 496 */ "TO_ALTERED_POST_SWAP",
        /* 497 */ "FROM_ALTERED_POST_SWAP",
        /* 498 */ "FLY_TO_ALTERED_POST_SWAP",
        /* 499 */ "FLY_FROM_ALTERED_POST_SWAP",
        /* 500 */ "RECLINED_MOUNT_PASSENGER",
        /* 501 */ "FLY_RECLINED_MOUNT_PASSENGER",
        /* 502 */ "CARRY_2H",
        /* 503 */ "CARRIED_2H",
        /* 504 */ "FLY_CARRY_2H",
        /* 505 */ "FLY_CARRIED_2H",
    };
    if (id < ANIM_COUNT) return names[id];
    return "UNKNOWN";
}
void validateAgainstDBC(const std::shared_ptr<wowee::pipeline::DBCFile>& dbc) {
    if (!dbc || !dbc->isLoaded()) {
        LOG_WARNING("AnimationData.dbc not available - skipping animation ID validation");
        return;
    }

    // Collect all IDs present in the DBC (first field is the animation ID)
    std::unordered_set<uint32_t> dbcIds;
    for (uint32_t i = 0; i < dbc->getRecordCount(); ++i) {
        uint32_t id = dbc->getUInt32(i, 0);
        dbcIds.insert(id);
    }

    // Check: constants we define that are missing from DBC
    uint32_t missingInDbc = 0;
    uint32_t firstMissingInDbc = ANIM_COUNT;
    uint32_t lastMissingInDbc = 0;
    for (uint32_t id = 0; id < ANIM_COUNT; ++id) {
        if (dbcIds.find(id) == dbcIds.end()) {
            if (missingInDbc == 0) firstMissingInDbc = id;
            lastMissingInDbc = id;
            ++missingInDbc;
        }
    }
    if (missingInDbc > 0) {
        LOG_WARNING("AnimationData.dbc validation: ", missingInDbc,
                    " animation constants are absent from this client DBC",
                    " (first=", firstMissingInDbc,
                    " ", nameFromId(firstMissingInDbc),
                    ", last=", lastMissingInDbc,
                    " ", nameFromId(lastMissingInDbc),
                    "); suppressing per-ID warnings");
    }

    // Check: DBC IDs beyond our constant range
    uint32_t extraInDbc = 0;
    for (uint32_t dbcId : dbcIds) {
        if (dbcId >= ANIM_COUNT) {
            ++extraInDbc;
        }
    }

    LOG_INFO("AnimationData.dbc validation: ", dbc->getRecordCount(), " DBC records, ",
             ANIM_COUNT, " constants, ",
             missingInDbc, " missing from DBC, ",
             extraInDbc, " DBC-only IDs beyond constant range");
}

} // namespace anim
} // namespace rendering
} // namespace wowee
